# Generated by Django 5.2.4 on 2025-08-11 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MotionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("motion_name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="MotionRecording",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                ("data_frames", models.IntegerField()),
                (
                    "score_category",
                    models.CharField(
                        choices=[
                            ("reference", "모범 동작"),
                            ("zero_score", "0점 동작"),
                        ],
                        max_length=20,
                    ),
                ),
                ("sensor_data_json", models.JSONField()),
                (
                    "motion_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recordings",
                        to="ai.motiontype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserRecording",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField()),
                ("sensor_data_json", models.JSONField()),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "motion_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ai.motiontype"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_recordings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
